// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6PPXusHvZxgzkNy9D_ohUsRAx_W1F-Y',
    appId: '1:1017207092249:web:dc539b3035df302493e688',
    messagingSenderId: '1017207092249',
    projectId: 'lung-care-35059',
    authDomain: 'lung-care-35059.firebaseapp.com',
    storageBucket: 'lung-care-35059.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUPhWvbjpjao-9vDrVEv7P-IIOKFZO4AU',
    appId: '1:1017207092249:android:3441a14e0658678e93e688',
    messagingSenderId: '1017207092249',
    projectId: 'lung-care-35059',
    storageBucket: 'lung-care-35059.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2GeQObyIf6IMGeTRrjXRSCfMw4LisYmw',
    appId: '1:1017207092249:ios:8580ce875e26a3e993e688',
    messagingSenderId: '1017207092249',
    projectId: 'lung-care-35059',
    storageBucket: 'lung-care-35059.firebasestorage.app',
    iosBundleId: 'com.example.lungCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2GeQObyIf6IMGeTRrjXRSCfMw4LisYmw',
    appId: '1:1017207092249:ios:8580ce875e26a3e993e688',
    messagingSenderId: '1017207092249',
    projectId: 'lung-care-35059',
    storageBucket: 'lung-care-35059.firebasestorage.app',
    iosBundleId: 'com.example.lungCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK6PPXusHvZxgzkNy9D_ohUsRAx_W1F-Y',
    appId: '1:1017207092249:web:7b227f6c066a4c3293e688',
    messagingSenderId: '1017207092249',
    projectId: 'lung-care-35059',
    authDomain: 'lung-care-35059.firebaseapp.com',
    storageBucket: 'lung-care-35059.firebasestorage.app',
  );
}
